from __future__ import annotations

# Compatibility facade: benchmark runners now live in fire_agent.benchmarks.
from .benchmarks import (
    BENCHMARK_SPECS,
    CANONICAL_RUNNERS,
    RUNNER_ALIASES,
    RUNNER_REGISTRY,
    BenchmarkRunner,
    FinDocResearchRunner,
    FinGAIARunner,
    FinRptRunner,
    FinSearchCompRunner,
    FinanceAgentBenchRunner,
)
from .benchmarks.common import (
    FINDOCRESEARCH_FIELD_SCHEMA,
    FINDOCRESEARCH_STRUCTURE,
    FINRPT_OFFICIAL_RESPONSE_FIELDS,
    FINRPT_SOLVER_EXCLUDED_FIELDS,
    JsonRow,
    extract_urls,
    first_present,
    jsonish_string,
    normalize_legacy_row,
    normalize_legacy_rows,
    normalize_text,
    parse_jsonish,
    read_jsonl,
    sanitize_file_stem,
    write_jsonl,
)

__all__ = [
    "BENCHMARK_SPECS",
    "CANONICAL_RUNNERS",
    "FINDOCRESEARCH_FIELD_SCHEMA",
    "FINDOCRESEARCH_STRUCTURE",
    "FINRPT_OFFICIAL_RESPONSE_FIELDS",
    "FINRPT_SOLVER_EXCLUDED_FIELDS",
    "RUNNER_ALIASES",
    "RUNNER_REGISTRY",
    "BenchmarkRunner",
    "FinDocResearchRunner",
    "FinGAIARunner",
    "FinRptRunner",
    "FinSearchCompRunner",
    "FinanceAgentBenchRunner",
    "JsonRow",
    "extract_urls",
    "first_present",
    "jsonish_string",
    "normalize_legacy_row",
    "normalize_legacy_rows",
    "normalize_text",
    "parse_jsonish",
    "read_jsonl",
    "sanitize_file_stem",
    "write_jsonl",
]
